//-----------------------------------------------------------------------------
//! for 1chip sim c program modify
//-----------------------------------------------------------------------------
//!@file: dsi_reg_define.sv
//! - Copyright(C) Renesas Electronics Corp. 2016 All rights reserved
//! - Copyright(C) Renesas Design Vietnam Co., Ltd  2016 All rights reserved
//!
//! $Rev$:
//! $Date$:
//! $Author$:
//!
//-----------------------------------------------------------------------------

//===========================DSI registers========================
#define    ISR                                               0x000
#define    LINKSR                                            0x010
#define    GPIR                                              0x080
#define    GPOR                                              0x084
#define    TXSETR                                            0x100
#define    HSCLKSETR                                         0x104
#define    ULPSSETR                                          0x108
#define    ULPSCR                                            0x10C
#define    RSTCR                                             0x110
#define    RSTSR                                             0x114
#define    DSISETR                                           0x120
#define    RXBUFSZR                                          0x124
#define    TXPPD0R                                           0x160
#define    TXPPD1R                                           0x164
#define    TXPPD2R                                           0x168
#define    TXPPD3R                                           0x16C
#define    RXSR                                              0x200
#define    RXSCR                                             0x204
#define    RXRINFOOWSCR                                      0x23C
#define    RXRINFOOWSR                                       0x238
#define    RXIER                                             0x208
#define    PRESPTOBTASETR                                    0x210
#define    PRESPTOLPSETR                                     0x214
#define    PRESPTOHSSETR                                     0x218
#define    AKEPLATIR                                         0x220
#define    AKEPACMSR                                         0x224
#define    AKEPSCR                                           0x228
#define    RXRSSR                                            0x230
#define    RXRSSCR                                           0x234
#define    RXRSS0R                                           0x240
#define    RXRSS1R                                           0x244
#define    RXRSS2R                                           0x248
#define    RXRSS3R                                           0x24C
#define    VI1RXRSSR                                         0x2A0
#define    RXPPD0R                                           0x2C0
#define    RXPPD1R                                           0x2C4
#define    RXPPD2R                                           0x2C8
#define    RXPPD3R                                           0x2CC
#define    HSTXTOSETR                                        0x2E0
#define    LRXHTOSETR                                        0x2E4
#define    TATOSETR                                          0x2E8
#define    FERRSR                                            0x300
#define    FERRSCR                                           0x304
#define    FERRIER                                           0x308
#define    OPMSWTMR                                          0x310
#define    CLSTPTSETR                                        0x314
#define    LPTRNSTSETR                                       0x318
#define    PLSR                                              0x320
#define    PLSCR                                             0x324
#define    PLIER                                             0x328
#define    SCALPSZR                                          0x330
#define    DLSWAPR                                           0x350
#define    VIRUNI0R                                          0x360
#define    VIRUNI1R                                          0x364
#define    VICH1SET0R                                        0x400
#define    VICH1SET1R                                        0x404
#define    VICH1SR                                           0x410
#define    VICH1SCR                                          0x414
#define    VICH1IER                                          0x418
#define    VICH1PPSETR                                       0x420
#define    VICH1VSSETR                                       0x428
#define    VICH1VPSETR                                       0x42C
#define    VICH1HSSETR                                       0x430
#define    VICH1HPSETR                                       0x434
#define    TMCR                                              0x540
#define    TM0SETR                                           0x550
#define    TM1SETR                                           0x554
#define    SQRUNIR                                           0x580
#define    SQCH0SET0R                                        0x5C0
#define    SQCH0SET1R                                        0x5C4
#define    SQCH0SR                                           0x5D0
#define    SQCH0SCR                                          0x5D4
#define    SQCH0IER                                          0x5D8
#define    SQCH0DPR                                          0x5E0
#define    SQCH0DPSETR                                       0x5E4
#define    SQCH1SET0R                                        0x600
#define    SQCH1SET1R                                        0x604
#define    SQCH1SR                                           0x610
#define    SQCH1SCR                                          0x614
#define    SQCH1IER                                          0x618
#define    SQCH1DPR                                          0x620
#define    SQCH1DPSETR                                       0x624
#define    SQCH0DSC00AR                                      0x780
#define    SQCH0DSC00BR                                      0x784
#define    SQCH0DSC00CR                                      0x788
#define    SQCH0DSC00DR                                      0x78C
#define    SQCH0DSC01AR                                      0x790
#define    SQCH0DSC01BR                                      0x794
#define    SQCH0DSC01CR                                      0x798
#define    SQCH0DSC01DR                                      0x79C
#define    SQCH0DSC02AR                                      0x7A0
#define    SQCH0DSC02BR                                      0x7A4
#define    SQCH0DSC02CR                                      0x7A8
#define    SQCH0DSC02DR                                      0x7AC
#define    SQCH0DSC03AR                                      0x7B0
#define    SQCH0DSC03BR                                      0x7B4
#define    SQCH0DSC03CR                                      0x7B8
#define    SQCH0DSC03DR                                      0x7BC
#define    SQCH0DSC04AR                                      0x7C0
#define    SQCH0DSC04BR                                      0x7C4
#define    SQCH0DSC04CR                                      0x7C8
#define    SQCH0DSC04DR                                      0x7CC
#define    SQCH0DSC05AR                                      0x7D0
#define    SQCH0DSC05BR                                      0x7D4
#define    SQCH0DSC05CR                                      0x7D8
#define    SQCH0DSC05DR                                      0x7DC
#define    SQCH0DSC06AR                                      0x7E0
#define    SQCH0DSC06BR                                      0x7E4
#define    SQCH0DSC06CR                                      0x7E8
#define    SQCH0DSC06DR                                      0x7EC
#define    SQCH0DSC07AR                                      0x7F0
#define    SQCH0DSC07BR                                      0x7F4
#define    SQCH0DSC07CR                                      0x7F8
#define    SQCH0DSC07DR                                      0x7FC
#define    SQCH1DSC00AR                                      0x800
#define    SQCH1DSC00BR                                      0x804
#define    SQCH1DSC00CR                                      0x808
#define    SQCH1DSC00DR                                      0x80C
#define    SQCH1DSC01AR                                      0x810
#define    SQCH1DSC01BR                                      0x814
#define    SQCH1DSC01CR                                      0x818
#define    SQCH1DSC01DR                                      0x81C
#define    SQCH1DSC02AR                                      0x820
#define    SQCH1DSC02BR                                      0x824
#define    SQCH1DSC02CR                                      0x828
#define    SQCH1DSC02DR                                      0x82C
#define    SQCH1DSC03AR                                      0x830
#define    SQCH1DSC03BR                                      0x834
#define    SQCH1DSC03CR                                      0x838
#define    SQCH1DSC03DR                                      0x83C
#define    SQCH1DSC04AR                                      0x840
#define    SQCH1DSC04BR                                      0x844
#define    SQCH1DSC04CR                                      0x848
#define    SQCH1DSC04DR                                      0x84C
#define    SQCH1DSC05AR                                      0x850
#define    SQCH1DSC05BR                                      0x854
#define    SQCH1DSC05CR                                      0x858
#define    SQCH1DSC05DR                                      0x85C
#define    SQCH1DSC06AR                                      0x860
#define    SQCH1DSC06BR                                      0x864
#define    SQCH1DSC06CR                                      0x868
#define    SQCH1DSC06DR                                      0x86C
#define    SQCH1DSC07AR                                      0x870
#define    SQCH1DSC07BR                                      0x874
#define    SQCH1DSC07CR                                      0x878
#define    SQCH1DSC07DR                                      0x87C
#define    SQCH1DSC08AR                                      0x880
#define    SQCH1DSC08BR                                      0x884
#define    SQCH1DSC08CR                                      0x888
#define    SQCH1DSC08DR                                      0x88C
#define    SQCH1DSC09AR                                      0x890
#define    SQCH1DSC09BR                                      0x894
#define    SQCH1DSC09CR                                      0x898
#define    SQCH1DSC09DR                                      0x89C
#define    SQCH1DSC10AR                                      0x8A0
#define    SQCH1DSC10BR                                      0x8A4
#define    SQCH1DSC10CR                                      0x8A8
#define    SQCH1DSC10DR                                      0x8AC
#define    SQCH1DSC11AR                                      0x8B0
#define    SQCH1DSC11BR                                      0x8B4
#define    SQCH1DSC11CR                                      0x8B8
#define    SQCH1DSC11DR                                      0x8BC
#define    SQCH1DSC12AR                                      0x8C0
#define    SQCH1DSC12BR                                      0x8C4
#define    SQCH1DSC12CR                                      0x8C8
#define    SQCH1DSC12DR                                      0x8CC
#define    SQCH1DSC13AR                                      0x8D0
#define    SQCH1DSC13BR                                      0x8D4
#define    SQCH1DSC13CR                                      0x8D8
#define    SQCH1DSC13DR                                      0x8DC
#define    SQCH1DSC14AR                                      0x8E0
#define    SQCH1DSC14BR                                      0x8E4
#define    SQCH1DSC14CR                                      0x8E8
#define    SQCH1DSC14DR                                      0x8EC
#define    SQCH1DSC15AR                                      0x8F0
#define    SQCH1DSC15BR                                      0x8F4
#define    SQCH1DSC15CR                                      0x8F8
#define    SQCH1DSC15DR                                      0x8FC
#define    SQCH1DSC16AR                                      0x900
#define    SQCH1DSC16BR                                      0x904
#define    SQCH1DSC16CR                                      0x908
#define    SQCH1DSC16DR                                      0x90C
#define    SQCH1DSC17AR                                      0x910
#define    SQCH1DSC17BR                                      0x914
#define    SQCH1DSC17CR                                      0x918
#define    SQCH1DSC17DR                                      0x91C
#define    SQCH1DSC18AR                                      0x920
#define    SQCH1DSC18BR                                      0x924
#define    SQCH1DSC18CR                                      0x928
#define    SQCH1DSC18DR                                      0x92C
#define    SQCH1DSC19AR                                      0x930
#define    SQCH1DSC19BR                                      0x934
#define    SQCH1DSC19CR                                      0x938
#define    SQCH1DSC19DR                                      0x93C
#define    SQCH1DSC20AR                                      0x940
#define    SQCH1DSC20BR                                      0x944
#define    SQCH1DSC20CR                                      0x948
#define    SQCH1DSC20DR                                      0x94C
#define    SQCH1DSC21AR                                      0x950
#define    SQCH1DSC21BR                                      0x954
#define    SQCH1DSC21CR                                      0x958
#define    SQCH1DSC21DR                                      0x95C
#define    SQCH1DSC22AR                                      0x960
#define    SQCH1DSC22BR                                      0x964
#define    SQCH1DSC22CR                                      0x968
#define    SQCH1DSC22DR                                      0x96C
#define    SQCH1DSC23AR                                      0x970
#define    SQCH1DSC23BR                                      0x974
#define    SQCH1DSC23CR                                      0x978
#define    SQCH1DSC23DR                                      0x97C
#define    SQCH1DSC24AR                                      0x980
#define    SQCH1DSC24BR                                      0x984
#define    SQCH1DSC24CR                                      0x988
#define    SQCH1DSC24DR                                      0x98C
#define    SQCH1DSC25AR                                      0x990
#define    SQCH1DSC25BR                                      0x994
#define    SQCH1DSC25CR                                      0x998
#define    SQCH1DSC25DR                                      0x99C
#define    SQCH1DSC26AR                                      0x9A0
#define    SQCH1DSC26BR                                      0x9A4
#define    SQCH1DSC26CR                                      0x9A8
#define    SQCH1DSC26DR                                      0x9AC
#define    SQCH1DSC27AR                                      0x9B0
#define    SQCH1DSC27BR                                      0x9B4
#define    SQCH1DSC27CR                                      0x9B8
#define    SQCH1DSC27DR                                      0x9BC
#define    SQCH1DSC28AR                                      0x9C0
#define    SQCH1DSC28BR                                      0x9C4
#define    SQCH1DSC28CR                                      0x9C8
#define    SQCH1DSC28DR                                      0x9CC
#define    SQCH1DSC29AR                                      0x9D0
#define    SQCH1DSC29BR                                      0x9D4
#define    SQCH1DSC29CR                                      0x9D8
#define    SQCH1DSC29DR                                      0x9DC
#define    SQCH1DSC30AR                                      0x9E0
#define    SQCH1DSC30BR                                      0x9E4
#define    SQCH1DSC30CR                                      0x9E8
#define    SQCH1DSC30DR                                      0x9EC
#define    SQCH1DSC31AR                                      0x9F0
#define    SQCH1DSC31BR                                      0x9F4
#define    SQCH1DSC31CR                                      0x9F8
#define    SQCH1DSC31DR                                      0x9FC
#define    DBGACR                                            0x700
#define    DBGIR                                             0x704
#define    DBGVICH1R                                         0x708
#define    IBRSETR                                           0x718
#define    SQCH0TXSETR                                       0x720
#define    SQCH1TXSETR                                       0x724
#define    SQRXSETR                                          0x738
#define    DBGCR                                             0x73C
#define    DBGSR                                             0x740
#define    DBGSCR                                            0x744
#define    DBGIER                                            0x748
#define    DBGRSTCR                                          0x750
#define    PPIOPTSETR                                        0x754
#define    PPIMON0R                                          0x758
#define    PPIMON1R                                          0x75C
#define    PPIMON2R                                          0x760
#define    PPIMON3R                                          0x764
#define    APPSELR                                           0x768
#define    APPMONR                                           0x76C
// DREG
#define    DPHYCTRL0                                         0x00
#define    DPHYTIM0                                          0x04
#define    DPHYTIM1                                          0x08
#define    DPHYTIM2                                          0x0c
#define    DPHYTIM3                                          0x10
#define    DPHYCTRL1                                         0x40
#define    DPHYTRIM0                                         0x44
#define    DPHYPPI0                                          0x48
#define    DPHYTEST0                                         0x4c
#define    DPHYTEST1                                         0x50
#define    DPHYEVAL0                                         0x54
#define    DPHYEVAL1                                         0x58
#define    DPHYEVAL2                                         0x5c
#define    DPHYSKW0                                          0x60
#define    DPHYTERM0                                         0x64
#define    DPHYDBG0                                          0x68
#define    DPHYDBG1                                          0x6c
#define    DPHYDBG2                                          0x70
#define    DPHYCALHSRX0                                      0x74
